### ISSUE TITLE
Peer Review (From Emily Su)

### ISSUE THREAD

**Issue by moonsdust** [HaoweiFan0912/Deaths-of-Shelter-Residents-in-Toronto#1]
# Opening statement summary

Overall, the paper is well-written so far!

# Strong positive points

The data section of the paper is very strong where you showcase the variables you are using and also how you are cleaning the data. 

# Critical improvements needed

- README.md needs to be updated so it’s not the default starter folder. Alongside this the LLM usage statement needs to be updated in README.md indicate what AI tools you used or if you did not use any LLMs at all.
- You should remove the .DS_Store files throughout your repository

# Suggestions for improvement:

1. I think you can elaborate more on how the data is obtained in your raw data subsection. For example, who is recording the data if you know. 
2. The abstract does a good job of addressing what you did, what you found, and why your topic matters. However, I think you can be more specific in your abstract about what you mean by “changing needs” (like the changing needs of who?)
3. You can remove the model and replication scripts from the scripts folder since it seems that you aren’t using them. 
4. For your linear regression model graph, I would update the axis titles to not include the underscores and change the theme so it’s consistent with your other graphs
5. What is the APA.csl file? 

# Evaluation:

Overall, you are on track to writing a good paper! 

***Estimated mark**:* 54.5/64

***Reason:***

- From what I have read so far, you are covering an interesting and important topic and it’s well-written. Just make sure to address the critical improvements I have mentioned in the review and consider the suggestions for improvement.
- Rubric: 
  - R is appropriately cited: 1
  - LLM usage: 1
  - Title: 1
  - Author, date, repo: 2
  - Abstract: 4
  - Introduction: 4
  - Data: 8
  - Measurement: 2.5
  - Prose: 4
  - Cross-references: 1
  - Graphs: 2
  - Referencing: 4
  - Commits: 2
  - Sketches: 2
  - Simulation: 4
  - Tests: 4
  - Reproducibility: 2
  - Code Style: 1

**Comment by HaoweiFan0912** [comment]
Thanks for your suggestions. They are helpful. And I've fixed what you mentioned above.

**Comment by HaoweiFan0912** [comment]
By the way, APA.csl is the file that tells Qmd which reference style to use. However, I've deleted it.
